### ISSUE TITLE
"breaks" with new anki version 2.1.55

### ISSUE THREAD

**Issue by gustavosmendes** [AnKingMed/AnkiRecolor#16]
#### Problem description

Anki's new version, 2.1.55, has changed some html classes. E.g. I cannot change background webview since it is named now as "--canvas".

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
2.1.55
```

#### Error message (if any)

no error message.

```

```

**Comment by BlueGreenMagick** [comment]
There are other changes as well on 2.1.55

Relevant commit: https://github.com/ankitects/anki/commit/8142176f841519b3ea9d2838fe68597c540d356f

**Comment by gustavosmendes** [comment]
Thank you for the feedback. Didn't know about these issues.

**Comment by BlueGreenMagick** [comment]
Reopening as this is a valid issue! (Just that it's a bigger scope than initially thought)

**Comment by khonkhortisan** [comment]
Anki Versión ⁨2.1.55 beta4 (e3c3405f)⁩ Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
on startup:
```
Error
Un complemento que has instalado ha fallado al cargarse. Si los problemas persisten, por favor ve a Herramientas> Menú de complementos o deshabilita este complemento.

Mientras cargando '⁨ReColor⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\688199788\__init__.py", line 2, in <module>
    from . import colors
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\688199788\colors.py", line 198, in <module>
    recolor_python()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\688199788\colors.py", line 52, in recolor_python
    theme_manager._apply_style(mw.app)
  File "aqt.theme", line 250, in _apply_style
  File "aqt.stylesheets", line 111, in button_styles
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str
```
opening browser:
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración:
Anki 2.1.55 (e3c3405f) Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.19043
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-16 11:45:33

Caught exception:
Traceback (most recent call last):
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1158, in onBrowse
  File "aqt", line 130, in open
  File "aqt.browser.browser", line 135, in __init__
  File "aqt.browser.browser", line 620, in setupSidebar
  File "aqt.browser.sidebar.tree", line 95, in __init__
  File "aqt.browser.sidebar.tree", line 107, in _setup_style
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str
```
the addons menu and error pop-up are colored, the browse window doesn't open.

**Comment by BlueGreenMagick** [comment]
Thanks for the reminder!
